### ISSUE TITLE
how to get report after solve?

### ISSUE THREAD

**Issue by MehmetCelik4** [asee/lp_select#4]
How to get variables values after "LPSolve::solve(@lp)"?,

i only get this  

Optimal solution                  15 after          1 iter.

Excellent numeric accuracy ||*|| = 0

**Comment by jamesprior** [comment]
Gooood question, the readme seems a little slim on that point.  See https://github.com/asee/lp_select/blob/master/test/lp_select_test.rb for an easier example of setting up, solving, and getting the results from a problem.

If you want to use LPSolve directly try https://github.com/asee/lp_select/blob/master/test/lp_solve_test.rb#L243

**Comment by MehmetCelik4** [comment]
thank you :)
